### ISSUE TITLE
GraphQL Error Unknown field `childImageSharp` on type `File`

### ISSUE THREAD

**Issue by asgeo1** [LeKoArts/gatsby-starter-portfolio-bella#3]
This is only a minor issue, and mostly posting this incase someone else has it and is stumped like I was.

Basically, I followed the instructions, but when I added my content into Prismic, I just used their default image - which was a gif file.  Apparently the image-sharp tool doesn't like Gif files, and gave this error.

I didn't quite understand for a while, but eventually worked it out.

I suppose it's possible in Prismic to update the config so you can't pick a gif? I'll have to look into that.

**Comment by LekoArts** [comment]
Where did you add that? To the header image? Or the content?

**Comment by LekoArts** [comment]
To my knowledge you can’t set a filetype for the images.
